name: Deploy GitHub Release Assets

on:
  workflow_call:
    secrets:
      TOKEN_TO_UPLOAD_ASSETS:
        required: true

jobs:
  deploy_github_release_assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v6
        with:
          name: dist-3.14
          path: ./dist/
      - run: ls -lr
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN_TO_UPLOAD_ASSETS }}
          file_glob: true
          file: ./dist/*
